export const AccountInitialValues = {
    supportEmail: "",
    businessName: "",
    shortName: "",
    website: "",
    password: "",
    adjutor: "",
    addressOne: "",
    addressTwo: "",
    city: "",
    state: "",
    country: "",
    rcNumber: "",
    memart: "",
    COC: "",
    companyLogo: "",
    companyIcon: "",
    accountNumber: "",
    bankName: "",
};
